export default {
  manual: [
    {
      type: "category",
      label: "시작하기",
      items: [{ type: "doc", id: "getting-started/index" }],
    },
    {
      type: "category",
      label: "bakerywave",
      items: [
        { type: "doc", id: "bakerywave/index" },
        { type: "doc", id: "bakerywave/cli" },
        { type: "doc", id: "bakerywave/config" },
      ],
    },
    {
      type: "category",
      label: "Luau",
      items: [
        { type: "doc", id: "luau/tags" },
        { type: "doc", id: "luau/types" },
      ],
    },
    {
      type: "category",
      label: "개발",
      items: [
        { type: "doc", id: "development/index" },
        { type: "doc", id: "development/contributing" },
        { type: "doc", id: "development/release" },
        { type: "doc", id: "development/tests/index" },
        { type: "doc", id: "development/tests/scenarios" },
        { type: "doc", id: "development/tests/fixture" },
      ],
    },
  ],
  reference: [{ type: "autogenerated", dirName: "reference" }],
};
